name: Node.js CI

on: [ push ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm --ws --if-present run build:ci
      - run: npm run lint
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - run: npm --ws --if-present run build:ci
  lint:
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm --ws --if-present run build:ci
      - run: npm run lint
